# Support Kanbu Development

Help us build the future of open-source project management with AI superpowers!

## Sponsorship Options
: hydro13

# Buy Me a Coffee
# Once you create an account at buymeacoffee.com, update with your username
# buy_me_a_coffee: kanbu

# Patreon
# Once you create an account at patreon.com, update with your username
# patreon: kanbu

# Ko-fi
# Once you create an account at ko-fi.com, update with your username
# ko_fi: kanbu
# GitHub Sponsors
github
