# Support Kanbu Development

Help us build the future of open-source project management with AI superpowers!

## Sponsorship Options

# GitHub Sponsors
github: hydro13

# Buy Me a Coffee
buy_me_a_coffee: kanbu

# Ko-fi
ko_fi: kanbu

# Patreon (coming soon)
# patreon: kanbu
